name: FashionOS CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '18'

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: TypeScript Check
      run: |
        pnpm typecheck
        # Count warnings and fail if > 0
        WARNING_COUNT=$(pnpm typecheck 2>&1 | grep -c "warning TS" || true)
        if [ "$WARNING_COUNT" -gt "0" ]; then
          echo "❌ Found $WARNING_COUNT TypeScript warnings"
          exit 1
        fi
        
    - name: Run Tests
      run: pnpm test --coverage
      
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      
    - name: Build
      run: pnpm build
      
    - name: Bundle Size Check
      run: |
        BUNDLE_SIZE=$(du -sb .next/static | awk '{print $1}')
        MAX_SIZE=$((5 * 1024 * 1024)) # 5MB
        if [ "$BUNDLE_SIZE" -gt "$MAX_SIZE" ]; then
          echo "❌ Bundle size exceeds 5MB limit"
          exit 1
        fi
        echo "✅ Bundle size: $(($BUNDLE_SIZE / 1024 / 1024))MB"

  accessibility:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run Accessibility Tests
      run: pnpm test __tests__/accessibility

  e2e:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Install Playwright
      run: pnpm playwright install --with-deps
      
    - name: Build
      run: pnpm build
      
    - name: Run E2E Tests
      run: pnpm test:e2e
      
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  performance:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Build
      run: pnpm build
      
    - name: Lighthouse CI
      uses: treosh/lighthouse-ci-action@v9
      with:
        configPath: './lighthouserc.json'
        uploadArtifacts: true
        temporaryPublicStorage: true